CREATE DATABASE Tickets
GO
USE Tickets
GO
CREATE TABLE tickets(
	Usuario VARCHAR(MAX),
	FechaCreacion DATETIME DEFAULT GETDATE(),
	FechaActualizacion DATETIME DEFAULT GETDATE(),
	Status VARCHAR(10) DEFAULT 'Abierto',
	IdTicket INT PRIMARY KEY IDENTITY(1,1)
)
